### ISSUE TITLE
Better API for tooltips

### ISSUE THREAD

**Issue by MobileMon** [FormidableLabs/victory-native-xl#158]
Trying to add a tooltip to a grouped bar chart is extremely complicated

The code should be obstructed from the user where the user only needs to pass a 'renderToolTip' function, where they can customize the look of it

The chart should be smart enough to know where to render it with what data value(s)

**Comment by owattenmaker** [comment]
I think it's pretty easy? The state gives you the value and you just have to use the offset from the state.

```tsx
<Rect x={state.x.position} y={state.y.position} />
```

Gives you higher granularity over what you're rendering, and how you want to render it. For instance sometimes you don't want to respect the Y value for your text but you wanna draw a circle on the point
```tsx
<Text x={state.x.position} y={10} text={state.y.value} />
<Circle x={state.x.position} y={state.y.position} r={3} />
```

No event handlers, call backs, etc. If you need to format the value of the tooltip before showing it you can use workets with `useDerivedValue`. 

Once you get your tooltip working how you like, it's easy to extract it into a separate component to use with the rest of your graphs. Otherwise you'd have to have a bunch of flags to change how it renders.
