### ISSUE TITLE
One data point not display chart, only axis [CartesianChart]

### ISSUE THREAD

**Issue by idanlevi1** [FormidableLabs/victory-native-xl#208]
I use `CartesianChart` and when the data is 1 length (one point) it looks like this:

![image](https://github.com/FormidableLabs/victory-native-xl/assets/21155847/6fc3751d-790f-4a17-9dc7-160aa05f185c)

How do you solve it? what is the best way to show a chart of one item?

```
victory-native: 40.0.4
react-native: 0.73.1
```

**Comment by zibs** [comment]
Hey @idanlevi1 it does look like this isn't nicely handled out of the box, so it's something we should look into handling better... but in the meantime, you might have success trying to use the `domain` prop like `domain={{ y: [0, 100], x: [0, 2] }}` etc. This will allow you to specify the domain ranges of the chart so that you can specify values that will allow the single data point to be visible within those rangs.

https://victory-native-xl-docs-5n8bc4jvi-formidable-labs.vercel.app/cartesian/cartesian-chart#domain

**Comment by masiddee** [comment]
Hey, @idanlevi1 this should be resolved with my PR here: https://github.com/FormidableLabs/victory-native-xl/pull/237
