### ISSUE TITLE
Add more precisions on animations in the documentation

### ISSUE THREAD

**Issue by ivan-robert** [FormidableLabs/victory-native-xl#217]
### Description

I am currently trying to make an animated bar chart. It should be dead simple, but it is almost impossible due to total absence of documentation.

Following doc, the "animate" prop should do everything for me and animate on data change. However what does data change mean ? My data comes from the backend, it is not supposed to change. If I change it via a state, it triggers a re-render hence nothing is animated. Victory takes care of all the conversion with "points" prop, so I tried linking every point to a sharedValue, useless the only value taken by the points are the first value of the shared value.

I think there is a whole section lacking on how to reproduce simple examples such as the moving bar chart used to "demonstrate performance". Because it is nott normal that while having used victory before, it is still impossible to do a simple animation with victory xl

### Proposal

Could you explain me please how I can animate my barchart ? I am struggling. The best would be to add some more code in the documentation

**Comment by zibs** [comment]
Hey @ivan-robert -- have you taken a look at the example app inside the repo? There are plenty of example animations in there. We could maybe draw more attention to that in the docs? Feel free to make a PR if you find anything helpful!

**Comment by mars-lan** [comment]
After banging my head against the table for hours, it turns out that animations for bar charts are not supported. Skia is unable to interpolate the path, so the following line will always return `false`:

https://github.com/FormidableLabs/victory-native-xl/blob/47ed789ef67d8eac48c5eacfb590a80448e21009/lib/src/hooks/useAnimatedPath.ts#L72

Will open a PR to update https://nearform.com/open-source/victory-native/docs/animated-paths so it's explicit that Bar Chart is not supported.
